[package]
name = "pocket-renderer"
version = "0.1.0"
authors = ["Jon Grimes <jong@spiceworks.com>"]

[dependencies]
image = "*"
sdl2 = "0.32"
num-rational = "0.1.42"

[dev-dependencies]
bencher = "*"

[[bench]]
name = "line"
harness = false